### ISSUE TITLE
Exception raised while the service is down

### ISSUE THREAD

**Issue by pratikghimire** [cmthakur/health-inspector#2]
## Expected Behavior
When ever the service is down, it is expected to return the error response.

## Actual Behavior
When the service was down, it raised error instead of returning error response.

## Steps to Reproduce the Problem
  1. Start rails server
  2. Check for health, shows status ok
  3. Bring down Postgres server
  4. Check for health, it will raise error

## Specifications

  - Version: 5.0.1
  - Platform: MacOS 10.13.4
  - Framework: Rails

**Comment by cmthakur** [comment]
The bug has been fixed in `version0.2`
